# Generated by Django 3.2.8 on 2022-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_application_name'),
        ('users', '0003_profile_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application',
        ),
        migrations.AddField(
            model_name='profile',
            name='application',
            field=models.ManyToManyField(blank=True, null=True, to='base.Application'),
        ),
    ]
