# Generated by Django 3.2.8 on 2022-05-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_application_name'),
        ('users', '0005_auto_20220530_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to='base.application'),
        ),
    ]
