# Generated by Django 3.2.8 on 2022-05-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application',
        ),
    ]
