# Generated by Django 3.2.8 on 2022-05-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220531_1526'),
        ('users', '0009_remove_profile_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application'),
        ),
    ]
