# Generated by Django 3.2.8 on 2022-05-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220530_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='school',
            new_name='schools',
        ),
    ]
