# Generated by Django 3.2.8 on 2022-05-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
