# Generated by Django 3.2.8 on 2022-05-31 10:45

from django.db import migrations, models
import django.db.models.deletion
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_application'),
        ('base', '0007_remove_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=tkinter.tix.Tree, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
