# Generated by Django 3.2.8 on 2022-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('other', 'other')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
